server:
  port: 9000

eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
spring:
  application:
    name: eureka-consumer # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径
EUREKA-PROVIDER:  #远程服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #策略
ribbon:
  ConnectTimeout: 1000 # 链接超时时间
# 设置当前的日志级别 debug，feign只支持记录debug级别的日志
logging:
  level:
    com.xiaohua: debug
# 开启feign对hystrix的支持
feign:
  circuitbreaker:
    enabled: true
